### ISSUE TITLE
League Standings table format

### ISSUE THREAD

**Issue by sartaj10** [ManrajGrover/football-cli#23]
## Description

When viewing the Serie A standings table, one of the columns was not formatted correctly. Could be because the team name is pretty long

![screen shot 2018-03-07 at 11 12 47 am](https://user-images.githubusercontent.com/5708022/37113150-5ea1eb46-21f9-11e8-97aa-0f5d907a6620.png)

### Versions

- NodeJS version (if applicable): v6.11.2
- Football CLI version: 0.13.12

## Steps to recreate

football standings -l SA
football standings -l ELC

## People to notify

@ManrajGrover

**Comment by ManrajGrover** [comment]
Hey, this looks like a bug in `cli-table` dependency. Upgrading to `cli-table2` seems to fix this. Thanks for reporting this. Will fix this soon.

**Comment by ManrajGrover** [comment]
This should be fixed in #25. I'll make a release soon and let you know. Till then, you can check if it fixes for you by checking out master.

**Comment by ManrajGrover** [comment]
@sartaj10 Made a release with this fix. Please try `v0.14.0` and let me know if it is fixed.
