### ISSUE TITLE
What does -d flag do?

### ISSUE THREAD

**Issue by sartaj10** [ManrajGrover/football-cli#24]
## Description

football fixtures -l PL -d 5 -t "Manchester United" -n

In this, what does the `-d` refer to?

### Versions

- NodeJS version (if applicable):
- Football CLI version:

## People to notify

@ManrajGrover

**Comment by ManrajGrover** [comment]
Hi @sartaj10,

`-d` flag is for checking upcoming or past fixtures in `d` number of days from today. There seems to be a typo in code which is why it does not show up in the help menu. Thanks for bringing this up.

**Comment by sartaj10** [comment]
Thanks!
