### ISSUE TITLE
Not able to see upcoming matches

### ISSUE THREAD

**Issue by murarisumit** [ManrajGrover/football-cli#38]
BUG REPORT
    Bug: {Not able to see upcoming matches for Argentina}

    SUGGESTION
    Suggestion: {Should be able to see, upcoming matches of team}

  ## Versions

- NodeJS version: v10.5.0
- Football CLI version:  Not able to get it. 
<img width="432" alt="image" src="https://user-images.githubusercontent.com/2667258/41878611-625aab8c-78f3-11e8-94ec-aba4b713682d.png">

### Error
Was not able to see upcoming match of argentina, which according to my timezone is today

 
### Expected behaviour
Should be able to see upcoming match

## Steps to recreate
Have added screenshot

<img width="511" alt="image" src="https://user-images.githubusercontent.com/2667258/41878513-0eeb302a-78f3-11e8-97b6-ae77f179300e.png">

**Comment by ManrajGrover** [comment]
Hi @murarisumit,

There is a [`--next`](https://github.com/ManrajGrover/football-cli#command-fixtures) flag which needs to be invoked for upcoming fixtures. The command defaults to past fixtures.

Here is the updated command:

```sh
$ football fixtures --next
```

Regarding version issue, I've raised a PR (#40) for it which should fix it.
