### ISSUE TITLE
Suggestion: format fixture.date to local time

### ISSUE THREAD

**Issue by danoscarmike** [ManrajGrover/football-cli#39]
## Description
`football fixtures` returns fixture date and time in the original time zone (or maybe UTC?)

### Suggestion
use moment.js local() to convert to user's local time
perhaps, add this an option using a flag or toggle in configuration

Happy to open if PR if you like?

**Comment by danoscarmike** [comment]
Looked into it even more ;)

You are absolutely correct and moment() does indeed try to set the user's local time. 

My own timezone settings were not configured correctly.  I'm now seeing results as expected:

me@mine:~ $ `football scores`
    `Denmark 0 vs. 0 France Yesterday at 7:00 AM`
    `Australia 0 vs. 2 Peru Yesterday at 7:00 AM`
    `Nigeria 1 vs. 2 Argentina Yesterday at 11:00 AM`
    `Iceland 1 vs. 2 Croatia Yesterday at 11:00 AM`
    `Mexico 0 vs. 3 Sweden Today at 7:00 AM`
    `Korea Republic 2 vs. 0 Germany Today at 7:00 AM`

Nice looking Pacific Times!

**Comment by ManrajGrover** [comment]
@danoscarmike Thank you for looking into it!

Hope you're enjoying the world cup. :D
