### ISSUE TITLE
sudo: football: command not found

### ISSUE THREAD

**Issue by blackinitial** [ManrajGrover/football-cli#44]
i cant run ```sudo football config```, and get notif ``` sudo: football: command not found ```
i used zsh shell in LinuxMint OS
how to fix this?

**Comment by blackinitial** [comment]
Yes, i can. but yesterday i can't get the result, issue with the token when token is correct

**Comment by blackinitial** [comment]
I entered token with ``` football config``` without sudo

**Comment by ManrajGrover** [comment]
Yup, documentation should be fixed and `sudo` should not be part of the command, unless required.

**Comment by ManrajGrover** [comment]
Closing this issue. Please feel free to open again if the problem persists.

**Comment by blackinitial** [comment]
Thanks for your reply..
